using GLPIDotNet_API.Dashboard.Common;

namespace GLPIDotNet_API.Dashboard.Administration
{
    public class Profile : Dashboard<Profile>
    {
        public string @interface { get; set; }
        public long? helpdesk_hardware { get; set; }
        public string[] helpdesk_item_type { get; set; }
        public object ticket_status { get; set; }
        public object problem_status { get; set; }
        public bool? create_ticket_on_login { get; set; }
        public long? tickettemplates_id { get; set; }
        public long? changetemplates_id { get; set; }
        public long? problemtemplates_id { get; set; }
        public object hange_status { get; set; }
        public object managed_domainrecordtypes { get; set; }
        public long? appliance { get; set; }
        public long? backup { get; set; }
        public long? bookmark_public { get; set; }
        public long? budget { get; set; }
        public long? cable_management { get; set; }
        public long? calendar { get; set; }
        public long? cartridge { get; set; }
        public long? certificate { get; set; }
        public long? change { get; set; }
        public long? changevalidation { get; set; }
        public long? cluster { get; set; }
        public long? computer { get; set; }
        public long? config { get; set; }
        public long? consumable { get; set; }
        public long? contact_enterprise { get; set; }
        public long? contract { get; set; }
        public long? dashboard { get; set; }
        public long? database { get; set; }
        public long? datacenter { get; set; }
        public long? device { get; set; }
        public long? devicesimcard_pinpuk { get; set; }
        public long? document { get; set; }
        public long? domain { get; set; }
        public long? dropdown { get; set; }
        public long? entity { get; set; }
        public long? externalevent { get; set; }
        public long? followup { get; set; }
        public long? global_validation { get; set; }
        public long? group { get; set; }
        public long? infocom { get; set; }
        public long? internet { get; set; }
        public long? inventory { get; set; }
        public long? itilcategory { get; set; }
        public long? itilfollowuptemplate { get; set; }
        public long? itiltemplate { get; set; }
        public long? knowbase { get; set; }
        public long? knowbasecategory { get; set; }
        public long? license { get; set; }
        public long? line { get; set; }
        public long? lineoperator { get; set; }
        public long? link { get; set; }
        public long? location { get; set; }
        public long? logs { get; set; }
        public long? monitor { get; set; }
        public long? networking { get; set; }
        public long? notification { get; set; }
        public long? password_update { get; set; }
        public long? pendingreason { get; set; }
        public long? peripheral { get; set; }
        public long? personalization { get; set; }
        public long? phone { get; set; }
        public long? planning { get; set; }
        public long? plugin_accounts { get; set; }
        public long? plugin_accounts_hash { get; set; }
        public long? plugin_accounts_my_groups { get; set; }
        public long? plugin_accounts_open_ticket { get; set; }
        public long? plugin_accounts_see_all_users { get; set; }
        public long? plugin_addressing { get; set; }
        public long? plugin_addressing_use_ping_in_equipment { get; set; }
        public long? plugin_archimap_open_ticket { get; set; }
        public long? plugin_archires { get; set; }
        public long? plugin_databases_open_ticket { get; set; }
        public long? plugin_datainjection_model { get; set; }
        public long? plugin_datainjection_use { get; set; }
        public long? plugin_domains { get; set; }
        public long? plugin_domains_dropdown { get; set; }
        public long? plugin_domains_open_ticket { get; set; }
        public long? plugin_environment { get; set; }
        public long? plugin_environment_accounts { get; set; }
        public long? plugin_environment_badges { get; set; }
        public long? plugin_environment_databases { get; set; }
        public long? plugin_environment_webapplications { get; set; }
        public long? plugin_fusioninventory_agent { get; set; }
        public long? plugin_fusioninventory_blacklist { get; set; }
        public long? plugin_fusioninventory_collect { get; set; }
        public long? plugin_fusioninventory_configsecurity { get; set; }
        public long? plugin_fusioninventory_configuration { get; set; }
        public long? plugin_fusioninventory_credential { get; set; }
        public long? plugin_fusioninventory_credentialip { get; set; }
        public long? plugin_fusioninventory_deploymirror { get; set; }
        public long? plugin_fusioninventory_esx { get; set; }
        public long? plugin_fusioninventory_group { get; set; }
        public long? plugin_fusioninventory_ignoredimportdevice { get; set; }
        public long? plugin_fusioninventory_importxml { get; set; }
        public long? plugin_fusioninventory_iprange { get; set; }
        public long? plugin_fusioninventory_lock { get; set; }
        public long? plugin_fusioninventory_menu { get; set; }
        public long? plugin_fusioninventory_networkequipment { get; set; }
        public long? plugin_fusioninventory_package { get; set; }
        public long? plugin_fusioninventory_printer { get; set; }
        public long? plugin_fusioninventory_remotecontrol { get; set; }
        public long? plugin_fusioninventory_reportnetworkequipment { get; set; }
        public long? plugin_fusioninventory_reportprinter { get; set; }
        public long? plugin_fusioninventory_rulecollect { get; set; }
        public long? plugin_fusioninventory_ruleentity { get; set; }
        public long? plugin_fusioninventory_ruleimport { get; set; }
        public long? plugin_fusioninventory_rulelocation { get; set; }
        public long? plugin_fusioninventory_selfpackage { get; set; }
        public long? plugin_fusioninventory_task { get; set; }
        public long? plugin_fusioninventory_unmanaged { get; set; }
        public long? plugin_fusioninventory_userinteractiontemplate { get; set; }
        public long? plugin_fusioninventory_wol { get; set; }
        public long? plugin_genericobject_dvrs { get; set; }
        public long? plugin_genericobject_types { get; set; }
        public long? plugin_karastock_history { get; set; }
        public long? plugin_karastock_order { get; set; }
        public long? plugin_karastock_stock { get; set; }
        public long? plugin_ocsinventoryng { get; set; }
        public long? plugin_ocsinventoryng_clean { get; set; }
        public long? plugin_ocsinventoryng_import { get; set; }
        public long? plugin_ocsinventoryng_link { get; set; }
        public long? plugin_ocsinventoryng_rule { get; set; }
        public long? plugin_ocsinventoryng_sync { get; set; }
        public long? plugin_ocsinventoryng_view { get; set; }
        public long? plugin_order_bill { get; set; }
        public long? plugin_order_order { get; set; }
        public long? plugin_order_reference { get; set; }
        public long? plugin_pdf { get; set; }
        public long? plugin_printercounters { get; set; }
        public long? plugin_printercounters_add_lower_records { get; set; }
        public long? plugin_printercounters_snmpset { get; set; }
        public long? plugin_printercounters_update_records { get; set; }
        public long? plugin_processmaker_case { get; set; }
        public long? plugin_processmaker_config { get; set; }
        public long? plugin_reports_applicationsbylocation { get; set; }
        public long? plugin_reports_doublons { get; set; }
        public long? plugin_reports_equipmentbygroups { get; set; }
        public long? plugin_reports_equipmentbylocation { get; set; }
        public long? plugin_reports_globalhisto { get; set; }
        public long? plugin_reports_histohard { get; set; }
        public long? plugin_reports_histoinst { get; set; }
        public long? plugin_reports_infocom { get; set; }
        public long? plugin_reports_iteminstall { get; set; }
        public long? plugin_reports_licenses { get; set; }
        public long? plugin_reports_licensesexpires { get; set; }
        public long? plugin_reports_listequipmentbylocation { get; set; }
        public long? plugin_reports_listgroups { get; set; }
        public long? plugin_reports_location { get; set; }
        public long? plugin_reports_order_deliveryinfos { get; set; }
        public long? plugin_reports_order_orderdelivery { get; set; }
        public long? plugin_reports_pcsbyentity { get; set; }
        public long? plugin_reports_printers { get; set; }
        public long? plugin_reports_rules { get; set; }
        public long? plugin_reports_searchinfocom { get; set; }
        public long? plugin_reports_softnotinstalled { get; set; }
        public long? plugin_reports_softversioninstallations { get; set; }
        public long? plugin_reports_statnightticketsbypriority { get; set; }
        public long? plugin_reports_statticketsbyentity { get; set; }
        public long? plugin_reports_statticketsbypriority { get; set; }
        public long? plugin_reports_statusertask { get; set; }
        public long? plugin_reports_transferreditems { get; set; }
        public long? plugin_reports_zombies { get; set; }
        public long? plugin_satisfaction { get; set; }
        public long? plugin_shellcommands { get; set; }
        public long? plugin_tasklists { get; set; }
        public long? plugin_tasklists_config { get; set; }
        public long? plugin_tasklists_see_all { get; set; }
        public long? plugin_typology { get; set; }
        public long? plugin_vip { get; set; }
        public long? plugin_webresources_resource { get; set; }
        public long? printer { get; set; }
        public long? problem { get; set; }
        public long? profile { get; set; }
        public long? project { get; set; }
        public long? projecttask { get; set; }
        public long? queuednotification { get; set; }
        public long? recurrentchange { get; set; }
        public long? reminder_public { get; set; }
        public long? reports { get; set; }
        public long? reservation { get; set; }
        public long? rssfeed_public { get; set; }
        public long? rule_asset { get; set; }
        public long? rule_dictionnary_dropdown { get; set; }
        public long? rule_dictionnary_printer { get; set; }
        public long? rule_dictionnary_software { get; set; }
        public long? rule_import { get; set; }
        public long? rule_ldap { get; set; }
        public long? rule_mailcollector { get; set; }
        public long? rule_softwarecategories { get; set; }
        public long? rule_ticket { get; set; }
        public long? search_config { get; set; }
        public long? shellcommands { get; set; }
        public long? show_group_hardware { get; set; }
        public long? slm { get; set; }
        public long? software { get; set; }
        public long? solutiontemplate { get; set; }
        public long? state { get; set; }
        public long? statistic { get; set; }
        public long? task { get; set; }
        public long? taskcategory { get; set; }
        public long? ticket { get; set; }
        public long? ticketcost { get; set; }
        public long? ticketrecurrent { get; set; }
        public long? ticketvalidation { get; set; }
        public long? transfer { get; set; }
        public long? typedoc { get; set; }
        public long? user { get; set; }

    }
}
